
name: Publish nexe builds
on:
  pull_request:
    branches: [main]

jobs:

  # Create nexe build for later use
  build_and_publish:
    name: Build nexe
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
        node_version: ['12.21.0', '14.16.0']

    steps:
      - uses: actions/checkout@v2
      - name: Get node details via .npmrc
        id: get_node_details
        run: echo "::set-output name=version::$(cat .nvmrc)"
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ steps.get_node_details.outputs.version }}

      - run: npm ci
      - name: Run nexe CD build
        id: run_cd
        run: ./bin/run_cd
        env:
          NODE_VERSION: ${{ matrix.node_version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CREATE_RELEASE: 'false' 
